language: android
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  ./gradlew build