language: android
jdk:
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  ./gradlew build